- name: Java installation
  hosts: apex_new_db
  become: true
  tasks:

    - name: Download the JDK binaries
      get_url:
        url: https://download.java.net/java/GA/jdk18.0.2.1/db379da656dc47308e138f21b33976fa/1/GPL/openjdk-18.0.2.1_linux-x64_bin.tar.gz
        dest: /etc/openjdk-18.0.2.1_linux-x64_bin.tar.gz
     
    - name: Unzip the downloaded file
      unarchive:
        src: /etc/openjdk-18.0.2.1_linux-x64_bin.tar.gz
        dest: /etc
        remote_src: yes
  
    - name: Create the file
      file:
        path: /etc/profile.d/java.sh
        state: touch

    - name: Add contents to the file
      blockinfile:  
        path: /etc/profile.d/java.sh
        block: |
          export JAVA_HOME="/etc/jdk-18.0.2.1"
          export PATH=$PATH:$JAVA_HOME/bin